- name: woke
  terms:
    - woke
  alternatives:
    - based
  severity: warning
  note: "the word 'woke' discriminates against people who like to sleep or may be permanently asleep (deceased individuals)"
